--
-- ONLY FOR DEVELOPMENT
--
ALTER SEQUENCE discount_card_comment_id_seq RESTART WITH 1000;
ALTER SEQUENCE discount_card_history_id_seq RESTART WITH  1000;
ALTER SEQUENCE discount_card_id_seq RESTART WITH  1000;
ALTER SEQUENCE tag_id_seq RESTART WITH  1000;
ALTER SEQUENCE book_card_id_seq RESTART WITH  1000;
ALTER SEQUENCE location_id_seq RESTART WITH  1000;
ALTER SEQUENCE person_id_seq RESTART WITH  1000;
ALTER SEQUENCE tag_card_id_seq RESTART WITH  1000;